# KapilOS Configuration

OS_NAME="KapilOS"
OS_VERSION="0.1"
CODENAME="Genesis"

BASE_DISTRO="Ubuntu 24.04.4 LTS"

KERNEL="Linux"

DESKTOP="GNOME"

DISPLAY_MANAGER="GDM"

PACKAGE_MANAGER="APT"

BUILD_SYSTEM="CMake"

STATUS="Development"
